import React, { useState } from "react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import {
  useGetUsersWithOneToTwoDirectRefsQuery,
  useGetUsersWithThreeToFiveDirectRefsQuery,
  useGetUsersWithSixToNineDirectRefsQuery,
  useGetUsersWithTenToTwentyFiveDirectRefsQuery,
  useGetUsersWithTwentySixToHundredDirectRefsQuery,
  useGetInactiveUsersQuery
} from "./reportsApiSlice";

const SimpleBusinessReportPDF = () => {
  const [pdfLoading1to2, setPdfLoading1to2] = useState(false);
  const [pdfLoading3to5, setPdfLoading3to5] = useState(false);
  const [pdfLoading6to9, setPdfLoading6to9] = useState(false);
  const [pdfLoading10to25, setPdfLoading10to25] = useState(false);
  const [pdfLoading26to100, setPdfLoading26to100] = useState(false);
  const [pdfLoadingInactive, setPdfLoadingInactive] = useState(false);

  // API queries
  const { data: oneToTwoData, isLoading: loading1to2 } = useGetUsersWithOneToTwoDirectRefsQuery();
  const { data: threeToFiveData, isLoading: loading3to5 } = useGetUsersWithThreeToFiveDirectRefsQuery();
  const { data: sixToNineData, isLoading: loading6to9 } = useGetUsersWithSixToNineDirectRefsQuery();
  const { data: tenToTwentyFiveData, isLoading: loading10to25 } = useGetUsersWithTenToTwentyFiveDirectRefsQuery();
  const { data: twentySixToHundredData, isLoading: loading26to100 } = useGetUsersWithTwentySixToHundredDirectRefsQuery();
  const { data: inactiveUsersData, isLoading: loadingInactive } = useGetInactiveUsersQuery();

  // Toast configuration
  const toastConfig = {
    position: "top-right",
    autoClose: 3000,
    hideProgressBar: false,
    closeOnClick: true,
    pauseOnHover: true,
    draggable: true,
  };

  const generatePdfReport = (data, title, category, reportType) => {
    const doc = new jsPDF();
    let yPosition = 20;

    // Helper function to add new page if needed
    const checkAddPage = (requiredSpace = 20) => {
      if (yPosition + requiredSpace > doc.internal.pageSize.height - 20) {
        doc.addPage();
        yPosition = 20;
        return true;
      }
      return false;
    };

    // Header
    doc.setFontSize(18);
    doc.setTextColor(32, 147, 74);
    doc.text(title.toUpperCase(), 105, yPosition, {
      align: "center",
    });
    yPosition += 15;

    // Report Details
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.text(
      `Generated on: ${new Date().toLocaleDateString("en-GB")}`,
      20,
      yPosition
    );
    yPosition += 8;
    doc.text(`Total Records: ${data?.data?.length || 0}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Report Type: ${title}`, 20, yPosition);
    yPosition += 15;

    // Summary Section
    checkAddPage(30);
    doc.setFontSize(14);
    doc.setTextColor(32, 147, 74);
    doc.text("REPORT SUMMARY", 20, yPosition);
    yPosition += 10;

    if (reportType === 'inactive') {
      // Summary for inactive users
      const summaryData = [
        ["Metric", "Value"],
        ["Report Type", title || "N/A"],
        ["Total Users", (data?.data?.length || 0).toString()],
        ["Generated On", new Date().toLocaleDateString("en-GB")],
        ["Generated By", "Admin Portal"],
        ["Status", "Current Data"],
      ];

      autoTable(doc, {
        head: [summaryData[0]],
        body: summaryData.slice(1),
        startY: yPosition,
        theme: "striped",
        headStyles: {
          fillColor: [32, 147, 74],
          textColor: 255,
          fontSize: 10,
          fontStyle: "bold",
        },
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        columnStyles: {
          0: { cellWidth: 80 },
          1: { cellWidth: 80 },
        },
      });
    } else {
      // Summary for referral reports
      const totalUsers = data?.data?.length || 0;
      const totalDirectRefs = data?.data?.reduce((sum, user) => sum + (user.directRefs || 0), 0) || 0;
      const totalChainRefs = data?.data?.reduce((sum, user) => sum + (user.chainRefs || 0), 0) || 0;
      const totalRefs = data?.data?.reduce((sum, user) => sum + (user.totalRefs || 0), 0) || 0;

      const summaryData = [
        ["Metric", "Count/Value"],
        ["Total Users", totalUsers.toString()],
        ["Total Direct Refs Count", totalDirectRefs.toString()],
        ["Total Chain Refs Count", totalChainRefs.toString()],
        ["Overall Total Refs", totalRefs.toString()],
      ];

      autoTable(doc, {
        head: [summaryData[0]],
        body: summaryData.slice(1),
        startY: yPosition,
        theme: "striped",
        headStyles: {
          fillColor: [32, 147, 74],
          textColor: 255,
          fontSize: 10,
          fontStyle: "bold",
        },
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        columnStyles: {
          0: { cellWidth: 100 },
          1: { cellWidth: 50, halign: "right" },
        },
      });
    }

    yPosition = doc.lastAutoTable.finalY + 15;

    // Main Table
    if (data?.data?.length > 0) {
      checkAddPage(30);

      doc.setFontSize(14);
      doc.setTextColor(32, 147, 74);
      
      if (reportType === 'inactive') {
        doc.text("DETAILED USER DATA", 20, yPosition);
      } else {
        doc.text(`USERS WITH ${category} DIRECT REFERRALS`, 20, yPosition);
      }
      yPosition += 10;

      let tableColumns, tableRows, columnStyles;

      if (reportType === 'inactive') {
        // Inactive users table structure
        tableColumns = ["S.No", "Username", "Name", "Email", "Phone", "Referred By"];
        
        tableRows = data.data.map((user, index) => [
          (index + 1).toString(),
          user.username || "N/A",
          user.name || "N/A",
          user.email || "N/A",
          user.phone ? user.phone.toString() : "N/A",
          user.referenceId || "N/A",
        ]);

        columnStyles = {
          0: { cellWidth: 15 }, // S.No
          1: { cellWidth: 30 }, // Username
          2: { cellWidth: 35 }, // Name
          3: { cellWidth: 40 }, // Email
          4: { cellWidth: 30 }, // Phone
          5: { cellWidth: 30 }, // Referred By
        };
      } else {
        // Referral users table structure
        tableColumns = [
          "S.No",
          "Name",
          "Username",
          "Email",
          "Phone",
          "DR",
          "CR",
          "TR",
        ];

        tableRows = data.data.map((user, index) => [
          (index + 1).toString(),
          user.name || "N/A",
          user.username || "N/A",
          user.email || "N/A",
          user.phone?.toString() || "N/A",
          user.directRefs?.toString() || "0",
          user.chainRefs?.toString() || "0",
          user.totalRefs?.toString() || "0",
        ]);

        columnStyles = {
          0: { cellWidth: 15 },
          1: { cellWidth: 30 },
          2: { cellWidth: 30 },
          3: { cellWidth: 35 },
          4: { cellWidth: 25 },
          5: { cellWidth: 15 },
          6: { cellWidth: 15 },
          7: { cellWidth: 15 },
        };
      }

      autoTable(doc, {
        head: [tableColumns],
        body: tableRows,
        startY: yPosition,
        theme: "striped",
        headStyles: {
          fillColor: [32, 147, 74],
          textColor: 255,
          fontSize: reportType === 'inactive' ? 9 : 8,
          fontStyle: "bold",
        },
        styles: {
          fontSize: reportType === 'inactive' ? 8 : 7,
          cellPadding: 2,
        },
        columnStyles: columnStyles,
        didDrawPage: function (data) {
          let str = "Page " + doc.internal.getNumberOfPages();
          doc.setFontSize(8);
          doc.setTextColor(100);
          doc.text(
            str,
            data.settings.margin.left,
            doc.internal.pageSize.height - 10
          );
        },
      });

      yPosition = doc.lastAutoTable.finalY + 15;
    }

    // Insights Section for inactive users
    if (reportType === 'inactive' && data?.data?.length > 0) {
      checkAddPage(20);

      doc.setFontSize(14);
      doc.setTextColor(32, 147, 74);
      doc.text("INSIGHTS", 20, yPosition);
      yPosition += 10;

      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);

      const insights = [
        `• Total inactive users identified: ${data.data.length}`,
        `• These users may require re-engagement campaigns`,
        `• Consider targeted marketing strategies to reactivate these users`,
        `• Analyze user behavior patterns to understand inactivity reasons`,
        `• Implement automated email sequences for user re-activation`,
      ];

      insights.forEach((insight) => {
        checkAddPage(8);
        doc.text(insight, 20, yPosition);
        yPosition += 6;
      });
    }

    return doc;
  };

  const handlePdfGeneration = async (reportType) => {
    let data, title, category, setLoading, filename;

    switch (reportType) {
      case 'inactive':
        data = inactiveUsersData;
        title = "Inactive Users Report";
        category = "INACTIVE";
        setLoading = setPdfLoadingInactive;
        filename = `inactive-users-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      case '1to2':
        data = oneToTwoData;
        title = "Users with 1-2 Direct Referrals Report";
        category = "1-2";
        setLoading = setPdfLoading1to2;
        filename = `users-1-to-2-direct-refs-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      case '3to5':
        data = threeToFiveData;
        title = "Users with 3-5 Direct Referrals Report";
        category = "3-5";
        setLoading = setPdfLoading3to5;
        filename = `users-3-to-5-direct-refs-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      case '6to9':
        data = sixToNineData;
        title = "Users with 6-9 Direct Referrals Report";
        category = "6-9";
        setLoading = setPdfLoading6to9;
        filename = `users-6-to-9-direct-refs-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      case '10to25':
        data = tenToTwentyFiveData;
        title = "Users with 10-25 Direct Referrals Report";
        category = "10-25";
        setLoading = setPdfLoading10to25;
        filename = `users-10-to-25-direct-refs-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      case '26to100':
        data = twentySixToHundredData;
        title = "Users with 26-100 Direct Referrals Report";
        category = "26-100";
        setLoading = setPdfLoading26to100;
        filename = `users-26-to-100-direct-refs-report-${new Date().toISOString().split("T")[0]}.pdf`;
        break;
      default:
        return;
    }

    try {
      setLoading(true);

      const pdfDoc = generatePdfReport(data, title, category, reportType);

      if (pdfDoc) {
        pdfDoc.save(filename);
        toast.success(
          `${title} generated and downloaded successfully!`,
          toastConfig
        );
      } else {
        throw new Error("Failed to generate PDF content");
      }
    } catch (error) {
      console.error("PDF generation error:", error);
      toast.error(
        "Failed to generate PDF report. Please try again.",
        toastConfig
      );
    } finally {
      setLoading(false);
    }
  };

  const ReportCard = ({ title, count, isLoading, reportType, pdfLoading, bgColor, textColor }) => (
    <div className="col-lg-4 col-md-6 mb-4">
      <div className="card h-100" style={{ backgroundColor: "#1b232d", border: "1px solid #3a3a3a" }}>
        <div className="card-body d-flex flex-column">
          <h5 className={`card-title text-center mb-3 ${textColor}`}>{title}</h5>
          
          {isLoading ? (
            <div className="text-center py-4 flex-grow-1 d-flex align-items-center justify-content-center">
              <div>
                <div className="spinner-border text-primary" role="status">
                  <span className="visually-hidden">Loading...</span>
                </div>
                <p className="text-white mt-2 mb-0">Loading data...</p>
              </div>
            </div>
          ) : (
            <>
              <div className="text-center mb-4 flex-grow-1 d-flex align-items-center justify-content-center flex-column">
                <div className={`border rounded p-3 w-100`} style={{ borderColor: "#3a3a3a" }}>
                  <p className="h2 text-white mb-1">{count || 0}</p>
                  <small className="text-white">Users</small>
                </div>
              </div>
              
              <div className="text-center mt-auto">
                <button
                  className="btn px-3 py-2 w-100"
                  onClick={() => handlePdfGeneration(reportType)}
                  disabled={pdfLoading}
                  style={{
                    backgroundColor: bgColor,
                    border: `1px solid ${bgColor}`,
                    color: "#fff",
                    transition: "all 0.3s ease",
                    fontWeight: "600",
                    fontSize: "14px",
                  }}
                >
                  {pdfLoading ? (
                    <>
                      <span className="spinner-border spinner-border-sm me-2" role="status"></span>
                      Generating...
                    </>
                  ) : (
                    <>
                      📄 Generate PDF
                    </>
                  )}
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );

  return (
    <section className="profile_section py-4">
      <div className="container-fluid">
        <div className="rounded-3 px-3 pb-4 py-4 bg-dark text-white">
          <h2 className="mb-4 text-center text-md-start">
            Business Performance Reports
          </h2>
          <p className="mb-4">Generate individual PDF reports for different user categories based on their activity and referrals count.</p>

          <div className="row">
            {/* Inactive Users Report */}
            <ReportCard
              title="Inactive Users"
              count={inactiveUsersData?.data?.length}
              isLoading={loadingInactive}
              reportType="inactive"
              pdfLoading={pdfLoadingInactive}
              bgColor="#dc3545"
              textColor="text-danger"
            />

            <ReportCard
              title="1-2 Direct Referrals"
              count={oneToTwoData?.data?.length}
              isLoading={loading1to2}
              reportType="1to2"
              pdfLoading={pdfLoading1to2}
              bgColor="#17a2b8"
              textColor="text-info"
            />

            <ReportCard
              title="3-5 Direct Referrals"
              count={threeToFiveData?.data?.length}
              isLoading={loading3to5}
              reportType="3to5"
              pdfLoading={pdfLoading3to5}
              bgColor="#007bff"
              textColor="text-primary"
            />

            <ReportCard
              title="6-9 Direct Referrals"
              count={sixToNineData?.data?.length}
              isLoading={loading6to9}
              reportType="6to9"
              pdfLoading={pdfLoading6to9}
              bgColor="#ffc107"
              textColor="text-warning"
            />

            <ReportCard
              title="10-25 Direct Referrals"
              count={tenToTwentyFiveData?.data?.length}
              isLoading={loading10to25}
              reportType="10to25"
              pdfLoading={pdfLoading10to25}
              bgColor="#fd7e14"
              textColor="text-warning"
            />

            <ReportCard
              title="26-100 Direct Referrals"
              count={twentySixToHundredData?.data?.length}
              isLoading={loading26to100}
              reportType="26to100"
              pdfLoading={pdfLoading26to100}
              bgColor="#28a745"
              textColor="text-success"
            />
          </div>
        </div>
      </div>
    </section>
  );
};

export default SimpleBusinessReportPDF;